name: CI pipeline


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    

jobs:
  validate-and-package:
    runs-on: ubuntu-latest

    services:
      

    steps:
     
      - name: Checkout Source Code
        uses: actions/checkout@v4

      
      - name: Set Up Java 21 Environment
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'  

      
      
      - name: Execute Isolated Unit Tests
        run: mvn clean test

      
      - name: Validate Production Docker Image Construction
        run: |
          docker build -t biblioteka-app:latest .

